### ISSUE TITLE
Compatibility regression: `#[schemars(default)]` now validates types

### ISSUE THREAD

**Issue by teozkr** [GREsau/schemars#144]
Schemars used to just serialize whatever default value it was given, but #83 requires that the type of each field's default must match the type of the field itself. This used to work fine in 0.8.8, but doesn't in 0.8.9:

```rust
#[derive(schemars::JsonSchema)]
struct Foo {
    #[schemars(default = "default_value")]
    value: String,
}

fn default_value() -> serde_json::Value {
    serde_json::json!(null)
}
```

I think this makes sense in theory, but it should at least have been published as the semver-incompatible 0.9.0 instead.

We (@stackabletech) also use this as an escape hatch to work around #137, so it'd be nice to get that working (I'd be happy to submit a PR if you'd be ok with what's outlined in that ticket), and/or keep some sort of escape hatch around.

(Co-discovered with @sbernauer)

**Comment by BrynCooke** [comment]
The new functionality is problematic for us. We currently using the `with` option to completely change the type for the Json schema.

For instance this field:
```
  #[schemars(with = "Option<String>", default = "client_name_header_default_str")]
    #[serde(
        deserialize_with = "deserialize_header_name",
        default = "client_name_header_default"
    )]
    pub client_name_header: HeaderName,
```

Gives a compile error:
```
error[E0605]: non-primitive cast: `&'static str` as `http::header::HeaderName`
 --> apollo-router/src/plugins/telemetry/apollo.rs:9:37
  |
9 | #[derive(Debug, Clone, Deserialize, JsonSchema)]
  |                                     ^^^^^^^^^^ an `as` expression can only be used to convert between primitive types or to coerce to a specific trait object
  |
  = note: this error originates in the derive macro `JsonSchema` (in Nightly builds, run with -Z macro-backtrace for more info)

```
But the whole point of using 'with' was to change the type to something other than the original type that was more Json schema friendly.

**Comment by GREsau** [comment]
This breaking change was not intended - I'll back out the change from #83 and release a new version
