### ISSUE TITLE
the trait `rocket_okapi::JsonSchema` is not implemented for custom_model after ugrade from 0.7.6 to 0.8.3

### ISSUE THREAD

**Issue by megametres** [GREsau/schemars#106]
Hi,

On my api ( https://github.com/megametres/recettes-api ) after upgrading schemars ( from 0.7.6 to 0.8.3 ), I received the following error:
`error[E0277]: the trait bound `model_input_url::InputUrl: rocket_okapi::JsonSchema` is not satisfied
  --> src/main.rs:87:1
   |
87 | #[openapi]
   | ^^^^^^^^^^ the trait rocket_okapi::JsonSchema is not implemented for model_input_url::InputUrl
   |
   = note: required because of the requirements on the impl of OpenApiFromData<'_> for rocket_contrib::json::Json<model_input_url::InputUrl>
note: required by request_body
  --> /home/vscode/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket_okapi-0.5.1/src/request/mod.rs:19:5
   |
19 |     fn request_body(gen: &mut OpenApiGenerator) -> Result<RequestBody>;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   = note: this error originates in the attribute macro openapi (in Nightly builds, run with -Z macro-backtrace for more info)
`

The InputUrl model derive JsonSchema so I am a bit confused if it is an error on my end or if it is a regression?

Thanks and have a good day
